from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Afiliado(models.Model):# Creación de la tabla con el nombre Afiliado
    # Campos de la tabla
    
    MUNICIPIO_CHOICES = [
        ('ANACO', 'ANACO'),
        ('ARAGUA', 'ARAGUA'),
        ('BOLIVAR', 'BOLIVAR'),
        ('BRUZUAL', 'BRUZUAL'),
        ('CAJIGAL', 'CAJIGAL'),
        ('CAPISTRANO', 'CAPISTRANO'),
        ('CARVAJAL', 'CARVAJAL'),
        ('FREITES', 'FREITES'),
        ('GUANIPA', 'GUANIPA'),
        ('GUANTA', 'GUANTA'),
        ('INDEPENDENCIA', 'INDEPENDENCIA'),
        ('LIBERTAD', 'LIBERTAD'),
        ('McGREGOR', 'McGREGOR'),
        ('MIRANDA', 'MIRANDA'),
        ('MONAGAS', 'MONAGAS'),
        ('PEÑALVER', 'PEÑALVER'),
        ('PIRITU', 'PIRITU'),
        ('S.RODRIGUEZ', 'S.RODRIGUEZ'),
        ('SOTILLO', 'SOTILLO'),
        ('STA ANA', 'STA ANA'),
        ('URBANEJA', 'URBANEJA'),
    ]
    
    PROFESSION_CHOICES = [
        ('99 NO CLASIFICADOS', '99 NO CLASIFICADOS'),
        ('BACHILLER I', 'BACHILLER I'),
        ('BACHILLER II', 'BACHILLER II'),
        ('BACHILLER III', 'BACHILLER III'),
        ('PROF. UNIV. MEDICO I', 'PROF. UNIV. MEDICO I'),
        ('PROF.UNIV. ODONTOLOGO I', 'PROF.UNIV. ODONTOLOGO I'),
        ('PROFESIONAL UNIV. I', 'PROFESIONAL UNIV. I'),
        ('PROFESIONAL UNIV. II', 'PROFESIONAL UNIV. II'),
        ('PROFESIONAL UNIV.III', 'PROFESIONAL UNIV.III'),
        ('TSU I', 'TSU I'),
        ('TSU II', 'TSU II'),
    ]
    
    PLANTEL_CHOICES = [ 
        ('AA DR JOSE BERNARDO GOMEZ', 'AA DR JOSE BERNARDO GOMEZ'), 
        ('C B- BOYACA', 'C B- BOYACA'), 
        ('C B- CAMINO NUEVO', 'C B- CAMINO NUEVO'), 
        ('C B-ANACO', 'C B-ANACO'), 
        ('C B-ARAGUA DE BARCELONA', 'C B-ARAGUA DE BARCELONA'), 
        ('C B-AUGUSTO D AUBETERRE', 'C B-AUGUSTO D AUBETERRE'), 
        ('C B-CRISTOBAL COLON', 'C B-CRISTOBAL COLON'), 
        ('C B-DR JESUS MARIA BIANCO', 'C B-DR JESUS MARIA BIANCO'), 
        ('C B-DR JOSE R DOMINGUEZ', 'C B-DR JOSE R DOMINGUEZ'), 
        ('C B-EL TIGRE', 'C B-EL TIGRE'), 
        ('C B-FRANCISCO SALIAS', 'C B-FRANCISCO SALIAS'), 
        ('C B-GUANIPA II', 'C B-GUANIPA II'), 
        ('C B-JOSE RAFAEL REVENGA', 'C B-JOSE RAFAEL REVENGA'), 
        ('C B-JOSE RAMON CAMEJO', 'C B-JOSE RAMON CAMEJO'), 
        ('C B-JOSE T ARREAZA C', 'C B-JOSE T ARREAZA C'), 
        ('C B-JUAN BAUTISTA BIDEAUX', 'C B-JUAN BAUTISTA BIDEAUX'), 
        ('C B-JUAN PABLO ROJAS', 'C B-JUAN PABLO ROJAS'), 
        ('C B-JULIAN T MAZA', 'C B-JULIAN T MAZA'), 
        ('C B-MANUEL REYES BRAVO', 'C B-MANUEL REYES BRAVO'), 
        ('C B-NARICUAL', 'C B-NARICUAL'), 
        ('C B-NICOLAS E NAVARRO', 'C B-NICOLAS E NAVARRO'), 
        ('C B-PEDRO M FREITES', 'C B-PEDRO M FREITES'), 
        ('C B-PUERTO LA CRUZ I', 'C B-PUERTO LA CRUZ I'), 
        ('C B-SANTA ANA', 'C B-SANTA ANA'), 
        ('C B-TOMAS I POTENTINI', 'C B-TOMAS I POTENTINI'), 
        ('C D-ASISTENCIAL', 'C D-ASISTENCIAL'), 
        ('C D-JOSE ANT ANZOATEGUI', 'C D-JOSE ANT ANZOATEGUI'), 
        ('C D-MERCEDES P FREITES', 'C D-MERCEDES P FREITES'), 
        ('C D-PARIAGUAN', 'C D-PARIAGUAN'), 
        ('C.B. LEONARDO CHIRINOS', 'C.B. LEONARDO CHIRINOS'), 
        ('CAIPA EDO ANZOATEGUI', 'CAIPA EDO ANZOATEGUI'), 
        ('CB DR ANDRES M HERNANDEZ', 'CB DR ANDRES M HERNANDEZ'), 
        ('CB RAFEL A. FERNANDEZ P', 'CB RAFEL A. FERNANDEZ P'), 
        ('CCB-ARAGUA BARCELONA', 'CCB-ARAGUA BARCELONA'), 
        ('CCB-GUANIPA', 'CCB-GUANIPA'), 
        ('CCB-SOLEDAD I', 'CCB-SOLEDAD I'), 
        ('CDI-CTRO DESARROLLO INF 6', 'CDI-CTRO DESARROLLO INF 6'), 
        ('CDI-NO 24', 'CDI-NO 24'), 
        ('CEA-29 DE MARZO', 'CEA-29 DE MARZO'), 
        ('CENDA JOSE A ANZOATEGUI', 'CENDA JOSE A ANZOATEGUI'), 
        ('CPE-AMERICA DE LEONI', 'CPE-AMERICA DE LEONI'), 
        ('DESP.DEL DIRECT. ZONA ANZ', 'DESP.DEL DIRECT. ZONA ANZ'), 
        ('DIV DE ADMINISTRACION Y S', 'DIV DE ADMINISTRACION Y S'), 
        ('DIV DE ASESORIA LEGAL', 'DIV DE ASESORIA LEGAL'), 
        ('DIV DE INFORMATICA Y SIST', 'DIV DE INFORMATICA Y SIST'), 
        ('DIV DE PERSONAL', 'DIV DE PERSONAL'), 
        ('E B-5 DE JULIO', 'E B-5 DE JULIO'), 
        ('E I-EUGENIO MENDOZA', 'E I-EUGENIO MENDOZA'), 
        ('EAU-URB ANACO', 'EAU-URB ANACO'), 
        ('EB ANTONIO JOSE DE SUCRE', 'EB ANTONIO JOSE DE SUCRE'), 
        ('EB ARTURO MICHELENA', 'EB ARTURO MICHELENA'), 
        ('EB DR JOSE MARIA VARGAS', 'EB DR JOSE MARIA VARGAS'), 
        ('EB FRANCISCO DE MIRANDA', 'EB FRANCISCO DE MIRANDA'), 
        ('EB ROMULO GALLEGOS', 'EB ROMULO GALLEGOS'), 
        ('EREB BICENTENARIO', 'EREB BICENTENARIO'), 
        ('EREB-CHORRERON', 'EREB-CHORRERON'), 
        ('EREB-SAN DIEGO', 'EREB-SAN DIEGO'), 
        ('EREB-SAN PEDRO', 'EREB-SAN PEDRO'), 
        ('ESC BOLIV OFICINA UNO', 'ESC BOLIV OFICINA UNO'), 
        ('ESC BOLIV SANTO DOMINGO', 'ESC BOLIV SANTO DOMINGO'), 
        ('ESC EL PAO', 'ESC EL PAO'), 
        ('ESC-BARRIO 29 DE MARZO', 'ESC-BARRIO 29 DE MARZO'), 
        ('ESC-BARRIO SUCRE', 'ESC-BARRIO SUCRE'), 
        ('ESC-CIUDAD LA ASUNCION', 'ESC-CIUDAD LA ASUNCION'), 
        ('ESC-DIEGO B URBANEJA', 'ESC-DIEGO B URBANEJA'), 
        ('ESC-DR DOMINGO GUZMAN L', 'ESC-DR DOMINGO GUZMAN L'), 
        ('ESC-DR JOSE B GOMEZ', 'ESC-DR JOSE B GOMEZ'), 
        ('ESC-DR JULIO CAMEJO', 'ESC-DR JULIO CAMEJO'), 
        ('ESC-ENRIQUE PEREZ V', 'ESC-ENRIQUE PEREZ V'), 
        ('ESC-EULALIA BUROZ', 'ESC-EULALIA BUROZ'), 
        ('ESC-FRAY NICOLAS DE ODENA', 'ESC-FRAY NICOLAS DE ODENA'), 
        ('ESC-GRAL JOSE ANZOATEGUI', 'ESC-GRAL JOSE ANZOATEGUI'), 
        ('ESC-GUARAGUAO', 'ESC-GUARAGUAO'), 
        ('ESC-INES M DE POTENTINI', 'ESC-INES M DE POTENTINI'), 
        ('ESC-J M PORRAS ALFARO', 'ESC-J M PORRAS ALFARO'), 
        ('ESC-LAS CHARAS', 'ESC-LAS CHARAS'), 
        ('ESC-MERCEDES DE PEREZ F', 'ESC-MERCEDES DE PEREZ F'), 
        ('ESC-PEDRO ROLIGSON HERRERA', 'ESC-PEDRO ROLIGSON HERRERA'), 
        ('ESC-RAFAEL MARCANO R', 'ESC-RAFAEL MARCANO R'), 
        ('ESC-RAFAEL MEDINA GARCIA', 'ESC-RAFAEL MEDINA GARCIA'), 
        ('ESC-SAN PABLO', 'ESC-SAN PABLO'), 
        ('ESC-SEVERIANO HERNANDEZ', 'ESC-SEVERIANO HERNANDEZ'), 
        ('ESC-VALLE LINDO', 'ESC-VALLE LINDO'), 
        ('ETA EL TIGRE', 'ETA EL TIGRE'), 
        ('ETA RAFAEL PEÐALVER', 'ETA RAFAEL PEÐALVER'), 
        ('ETA RICARDO ALFONZO ROJAS', 'ETA RICARDO ALFONZO ROJAS'), 
        ('ETA SILVESTRE G Y LIRA', 'ETA SILVESTRE G Y LIRA'), 
        ('ETC FELIPE GUEVARA ROJAS', 'ETC FELIPE GUEVARA ROJAS'), 
        ('G E- RAUL LEONI', 'G E- RAUL LEONI'), 
        ('G E-ANDRES E BLANCO', 'G E-ANDRES E BLANCO'), 
        ('G E-ANTONIO J SOTILLO', 'G E-ANTONIO J SOTILLO'), 
        ('G E-AUGUSTO DE AUBETERRE', 'G E-AUGUSTO DE AUBETERRE'), 
        ('G E-BLAS FARI/AS', 'G E-BLAS FARI/AS'), 
        ('G E-BOYACA', 'G E-BOYACA'), 
        ('G E-CACIQUE PAISANA', 'G E-CACIQUE PAISANA'), 
        ('G E-CAJIGAL', 'G E-CAJIGAL'), 
        ('G E-CARLOS FRAGACHAN', 'G E-CARLOS FRAGACHAN'), 
        ('G E-CARVAJAL', 'G E-CARVAJAL'), 
        ('G E-CELESTINO GONZALEZ', 'G E-CELESTINO GONZALEZ'), 
        ('G E-DR JOSE M COVA MAZA', 'G E-DR JOSE M COVA MAZA'), 
        ('G E-DR RAFAEL VELASQUEZ', 'G E-DR RAFAEL VELASQUEZ'), 
        ('G E-ESTADO TRUJILLO', 'G E-ESTADO TRUJILLO'), 
        ('G E-GUEVARA Y LIRA', 'G E-GUEVARA Y LIRA'), 
        ('G E-GUZMAN BASTARDO', 'G E-GUZMAN BASTARDO'), 
        ('G E-JOSE M SANTELIZ P', 'G E-JOSE M SANTELIZ P'), 
        ('G E-MONS ARTURO C ALVAREZ', 'G E-MONS ARTURO C ALVAREZ'), 
        ('G E-NARCISO FRAGACHAN', 'G E-NARCISO FRAGACHAN'), 
        ('G E-NICANOR BOLET PERAZA', 'G E-NICANOR BOLET PERAZA'), 
        ('G E-PEDRO C MU/OZ', 'G E-PEDRO C MU/OZ'), 
        ('G E-PIO CEBALLOS', 'G E-PIO CEBALLOS'), 
        ('G E-REP DE CHILE', 'G E-REP DE CHILE'), 
        ('G E-RODOLFO MAURERA', 'G E-RODOLFO MAURERA'), 
        ('G E-TOMAS IGN POTENTINI', 'G E-TOMAS IGN POTENTINI'), 
        ('G E-TOMAS MONTILLA', 'G E-TOMAS MONTILLA'), 
        ('G E-TRONCONAL IV', 'G E-TRONCONAL IV'), 
        ('I E E S0LEDAD', 'I E E S0LEDAD'), 
        ('ICN-FELIPE GUEVARA R', 'ICN-FELIPE GUEVARA R'), 
        ('IEE DR JOSE MARIA VARGAS', 'IEE DR JOSE MARIA VARGAS'), 
        ('IEE GUANIPA', 'IEE GUANIPA'), 
        ('IEE-AGUAPANE', 'IEE-AGUAPANE'), 
        ('IEE-ANACO', 'IEE-ANACO'), 
        ('IEE-BARCELONA', 'IEE-BARCELONA'), 
        ('IEE-EL TIGRE', 'IEE-EL TIGRE'), 
        ('IEE-PUERTO LA CRUZ', 'IEE-PUERTO LA CRUZ'), 
        ('IEE-ROMULO GALLEGOS', 'IEE-ROMULO GALLEGOS'), 
        ('IEE-SIMON RODRIGUEZ', 'IEE-SIMON RODRIGUEZ'), 
        ('J DE I PEDRO M FREITES', 'J DE I PEDRO M FREITES'), 
        ('J I-BARRIO CAYAURIMA', 'J I-BARRIO CAYAURIMA'), 
        ('J I-BLAS FARI/AS', 'J I-BLAS FARI/AS'), 
        ('J I-CELESTINO GONZALEZ', 'J I-CELESTINO GONZALEZ'), 
        ('J I-DON ANDRES BELLO', 'J I-DON ANDRES BELLO'), 
        ('J I-DR DOMINGO GUZMAN', 'J I-DR DOMINGO GUZMAN'), 
        ('J I-DR J M RODRIGUEZ A', 'J I-DR J M RODRIGUEZ A'), 
        ('J I-DR JULIO CAMEJO', 'J I-DR JULIO CAMEJO'), 
        ('J I-EULALIA BUROZ', 'J I-EULALIA BUROZ'), 
        ('J I-JOSE GIL FORTOUL', 'J I-JOSE GIL FORTOUL'), 
        ('J I-JOSE S GONZALEZ', 'J I-JOSE S GONZALEZ'), 
        ('J I-LA FLORIDA', 'J I-LA FLORIDA'), 
        ('J I-LUIS EZPELOSIN', 'J I-LUIS EZPELOSIN'), 
        ('J I-LUISA CACERES DE A', 'J I-LUISA CACERES DE A'), 
        ('J I-S JOSE DE GUANIPA', 'J I-S JOSE DE GUANIPA'), 
        ('JI BARRIO 23 DE ENERO', 'JI BARRIO 23 DE ENERO'), 
        ('L N-ANT PINTO SALINAS', 'L N-ANT PINTO SALINAS'), 
        ('L N-BRICE/O MENDEZ', 'L N-BRICE/O MENDEZ'), 
        ('L N-C DEL V RODRIGUEZ', 'L N-C DEL V RODRIGUEZ'), 
        ('L N-CAJIGAL', 'L N-CAJIGAL'), 
        ('L N-CRUZ DEL V RODRIGUEZ', 'L N-CRUZ DEL V RODRIGUEZ'), 
        ('L N-FELIPE GUEVARA ROJAS', 'L N-FELIPE GUEVARA ROJAS'), 
        ('L N-GUANIPA', 'L N-GUANIPA'), 
        ('L N-L ANT PINTO SALINAS', 'L N-L ANT PINTO SALINAS'), 
        ('L N-NARCISO FRAGACHAN', 'L N-NARCISO FRAGACHAN'), 
        ('L N-TOMAS ALFARO CALATRAVA', 'L N-TOMAS ALFARO CALATRAVA'), 
        ('L.BOLIVARIANO CHAMARIAPA', 'L.BOLIVARIANO CHAMARIAPA'), 
        ('LB JOSE FRNACISCO LAYA', 'LB JOSE FRNACISCO LAYA'), 
        ('LB SIMON RODRIGUEZ', 'LB SIMON RODRIGUEZ'), 
        ('LIC TOMAS ALFARO C', 'LIC TOMAS ALFARO C'), 
        ('NER LAS PLACITAS', 'NER LAS PLACITAS'), 
        ('NER-552', 'NER-552'), 
        ('NER-NUC ESC RURAL N 039', 'NER-NUC ESC RURAL N 039'), 
        ('NER-NUC ESC RURAL N 040', 'NER-NUC ESC RURAL N 040'), 
        ('NER-NUC ESC RURAL N 078', 'NER-NUC ESC RURAL N 078'), 
        ('NER-NUC ESC RURAL N 183', 'NER-NUC ESC RURAL N 183'), 
        ('NER-NUC ESC RURAL N 212', 'NER-NUC ESC RURAL N 212'), 
        ('NER-NUC ESC RURAL N 239', 'NER-NUC ESC RURAL N 239'), 
        ('NER-NUC ESC RURAL N 281', 'NER-NUC ESC RURAL N 281'), 
        ('NER-NUC ESC RURAL N 310', 'NER-NUC ESC RURAL N 310'), 
        ('NER-NUC ESC RURAL N 371', 'NER-NUC ESC RURAL N 371'), 
        ('NER-NUC ESC RURAL N 445', 'NER-NUC ESC RURAL N 445'), 
        ('NER-NUC ESC RURAL N 450', 'NER-NUC ESC RURAL N 450'), 
        ('NUCLEO ESCOLAR INDIGENA', 'NUCLEO ESCOLAR INDIGENA'), 
        ('NUCLEO ZONA 02', 'NUCLEO ZONA 02'), 
        ('O M EDUC INDG Y Z FRONT', 'O M EDUC INDG Y Z FRONT'), 
        ('OFIC DE SUPERV ZONA NO 02', 'OFIC DE SUPERV ZONA NO 02'), 
        ('P E BARRIO EL ESFUERZO', 'P E BARRIO EL ESFUERZO'), 
        ('P E-JOSE FELIX RIVAS', 'P E-JOSE FELIX RIVAS'), 
        ('P E-MARIA MONTESSORI', 'P E-MARIA MONTESSORI'), 
        ('PE. FRANCISCO FERRER', 'PE. FRANCISCO FERRER'), 
        ('SIN IDENTIFICACION', 'SIN IDENTIFICACION'), 
        ('TEL AGUAPANE', 'TEL AGUAPANE'), 
        ('TEL PUERTO LA CRUZ', 'TEL PUERTO LA CRUZ'), 
        ('TEV- TRONCONAL III', 'TEV- TRONCONAL III'), 
        ('U.E.D. DR. ALI GARCIA C.', 'U.E.D. DR. ALI GARCIA C.'), 
        ('UE CINCUENTENARIO', 'UE CINCUENTENARIO'), 
        ('UE. DR. JOSE MARIA VARGAS', 'UE. DR. JOSE MARIA VARGAS'), 
    ]   
    
    CARGO_CHOICES = {
        '99 NO CLASIFICADOS': '1000NC',
        'BACHILLER I': '100000',
        'BACHILLER II': '110000',
        'BACHILLER III': '110100',
        'PROF. UNIV. MEDICO I': '340201',
        'PROF.UNIV. ODONTOLOGO I': '340601',
        'PROFESIONAL UNIV. I': '300000',
        'PROFESIONAL UNIV. II': '310000',
        'PROFESIONAL UNIV.III': '310100',
        'TSU I': '200000',
        'TSU II': '210000',
    }
    
    CODPLANTEL_CHOICES = { 
        'AA DR JOSE BERNARDO GOMEZ' : '6513055', 
        'C B- BOYACA' : '7911739',
        'C B- CAMINO NUEVO' : '7912102',
        'C B-ANACO' : '7911154',
        'C B-ARAGUA DE BARCELONA' : '7911399',
        'C B-AUGUSTO D AUBETERRE' : '7911729',
        'C B-CRISTOBAL COLON' : '7917600',
        'C B-DR JESUS MARIA BIANCO' : '7918852',
        'C B-DR JOSE R DOMINGUEZ' : '7912154',
        'C B-EL TIGRE' : '7912821',
        'C B-FRANCISCO SALIAS' : '7913135',
        'C B-GUANIPA II' : '7913631',
        'C B-JOSE RAFAEL REVENGA' : '7914543',
        'C B-JOSE RAMON CAMEJO' : '7911945',
        'C B-JOSE T ARREAZA C' : '7917660',
        'C B-JUAN BAUTISTA BIDEAUX' : '7911706',
        'C B-JUAN PABLO ROJAS' : '5605130',
        'C B-JULIAN T MAZA' : '7918500',
        'C B-MANUEL REYES BRAVO' : '7913480',
        'C B-NARICUAL' : '7916322',
        'C B-NICOLAS E NAVARRO' : '7916870',
        'C B-PEDRO M FREITES' : '7917650',
        'C B-PUERTO LA CRUZ I' : '7917738',
        'C B-SANTA ANA' : '7918179',
        'C B-TOMAS I POTENTINI' : '7917190',
        'C D-ASISTENCIAL' : '5643703',
        'C D-JOSE ANT ANZOATEGUI' : '7914100',
        'C D-MERCEDES P FREITES' : '5650200',
        'C D-PARIAGUAN' : '7919340',
        'C.B. LEONARDO CHIRINOS' : '7911739',
        'CAIPA EDO ANZOATEGUI' : '6490281',
        'CB DR ANDRES M HERNANDEZ' : '7917739',
        'CB RAFEL A. FERNANDEZ P' : '7911602',
        'CCB-ARAGUA BARCELONA' : '7911503',
        'CCB-GUANIPA' : '7913475',
        'CCB-SOLEDAD I' : '7913481',
        'CDI-CTRO DESARROLLO INF 6' : '6412119',
        'CDI-NO 24' : '6412148',
        'CEA-29 DE MARZO' : '6391155',
        'CENDA JOSE A ANZOATEGUI' : '6490531',
        'CPE-AMERICA DE LEONI' : '6530154',
        'DESP.DEL DIRECT. ZONA ANZ' : '1200030',
        'DIV DE ADMINISTRACION Y S' : '1200035',
        'DIV DE ASESORIA LEGAL' : '1200031',
        'DIV DE INFORMATICA Y SIST' : '1200040',
        'DIV DE PERSONAL' : '1200039',
        'E B-5 DE JULIO' : '7933008',
        'E I-EUGENIO MENDOZA' : '5603500',
        'EAU-URB ANACO' : '6570100',
        'EB ANTONIO JOSE DE SUCRE' : '6590030',
        'EB ARTURO MICHELENA' : '6590175',
        'EB DR JOSE MARIA VARGAS' : '6739734',
        'EB FRANCISCO DE MIRANDA' : '7914984',
        'EB ROMULO GALLEGOS' : '6739732',
        'EREB BICENTENARIO' : '7940051',
        'EREB-CHORRERON' : '7940041',
        'EREB-SAN DIEGO' : '7940116',
        'EREB-SAN PEDRO' : '7940138',
        'ESC BOLIV OFICINA UNO' : '6590043',
        'ESC BOLIV SANTO DOMINGO' : '6589782',
        'ESC EL PAO' : '6563590',
        'ESC-BARRIO 29 DE MARZO' : '6561862',
        'ESC-BARRIO SUCRE' : '6561883',
        'ESC-CIUDAD LA ASUNCION' : '6562690',
        'ESC-DIEGO B URBANEJA' : '6562980',
        'ESC-DR DOMINGO GUZMAN L' : '6563660',
        'ESC-DR JOSE B GOMEZ' : '6561450',
        'ESC-DR JULIO CAMEJO' : '6561867',
        'ESC-ENRIQUE PEREZ V' : '6563878',
        'ESC-EULALIA BUROZ' : '6563955',
        'ESC-FRAY NICOLAS DE ODENA' : '6564305',
        'ESC-GRAL JOSE ANZOATEGUI' : '6565638',
        'ESC-GUARAGUAO' : '6564459',
        'ESC-INES M DE POTENTINI' : '6568475',
        'ESC-J M PORRAS ALFARO' : '6564780',
        'ESC-LAS CHARAS' : '6565715',
        'ESC-MERCEDES DE PEREZ F' : '6566390',
        'ESC-PEDRO ROLIGSON HERRERA' : '6565830',
        'ESC-RAFAEL MARCANO R' : '6567700',
        'ESC-RAFAEL MEDINA GARCIA' : '6561918',
        'ESC-SAN PABLO' : '6568080',
        'ESC-SEVERIANO HERNANDEZ' : '6562000',
        'ESC-VALLE LINDO' : '6568807',
        'ETA EL TIGRE' : '7911210',
        'ETA RAFAEL PEÐALVER' : '5511030',
        'ETA RICARDO ALFONZO ROJAS' : '7915920',
        'ETA SILVESTRE G Y LIRA' : '5650100',
        'ETC FELIPE GUEVARA ROJAS' : '5783600',
        'G E- RAUL LEONI' : '6738966',
        'G E-ANDRES E BLANCO' : '6731523',
        'G E-ANTONIO J SOTILLO' : '6731690',
        'G E-AUGUSTO DE AUBETERRE' : '6731865',
        'G E-BLAS FARI/AS' : '6732057',
        'G E-BOYACA' : '6732062',
        'G E-CACIQUE PAISANA' : '6732190',
        'G E-CAJIGAL' : '6732220',
        'G E-CARLOS FRAGACHAN' : '6732390',
        'G E-CARVAJAL' : '6732565',
        'G E-CELESTINO GONZALEZ' : '6732039',
        'G E-DR JOSE M COVA MAZA' : '6733740',
        'G E-DR RAFAEL VELASQUEZ' : '6733865',
        'G E-ESTADO TRUJILLO' : '6734590',
        'G E-GUEVARA Y LIRA' : '6735420',
        'G E-GUZMAN BASTARDO' : '6735460',
        'G E-JOSE M SANTELIZ P' : '6733745',
        'G E-MONS ARTURO C ALVAREZ' : '6737680',
        'G E-NARCISO FRAGACHAN' : '6737968',
        'G E-NICANOR BOLET PERAZA' : '6738010',
        'G E-PEDRO C MU/OZ' : '6738450',
        'G E-PIO CEBALLOS' : '6738593',
        'G E-REP DE CHILE' : '6739010',
        'G E-RODOLFO MAURERA' : '6739245',
        'G E-TOMAS IGN POTENTINI' : '6739700',
        'G E-TOMAS MONTILLA' : '6739705',
        'G E-TRONCONAL IV' : '6739733',
        'I E E S0LEDAD' : '6500338',
        'ICN-FELIPE GUEVARA R' : '5783605',
        'IEE DR JOSE MARIA VARGAS' : '6490419',
        'IEE GUANIPA' : '6417908',
        'IEE-AGUAPANE' : '6502580',
        'IEE-ANACO' : '6500070',
        'IEE-BARCELONA' : '6418005',
        'IEE-EL TIGRE' : '6502610',
        'IEE-PUERTO LA CRUZ' : '6412106',
        'IEE-ROMULO GALLEGOS' : '6418038',
        'IEE-SIMON RODRIGUEZ' : '6417947',
        'J DE I PEDRO M FREITES' : '4107847',
        'J I-BARRIO CAYAURIMA' : '4100940',
        'J I-BLAS FARI/AS' : '4101140',
        'J I-CELESTINO GONZALEZ' : '4101990',
        'J I-DON ANDRES BELLO' : '4102592',
        'J I-DR DOMINGO GUZMAN' : '4102790	',
        'J I-DR J M RODRIGUEZ A' : '4102930',
        'J I-DR JULIO CAMEJO' : '4102970',
        'J I-EULALIA BUROZ' : '4103690',
        'J I-JOSE GIL FORTOUL' : '4109365',
        'J I-JOSE S GONZALEZ' : '4105380',
        'J I-LA FLORIDA' : '4105961',
        'J I-LUIS EZPELOSIN' : '4109312',
        'J I-LUISA CACERES DE A' : '4106407',
        'J I-S JOSE DE GUANIPA' : '4102197',
        'JI BARRIO 23 DE ENERO' : '4100759',
        'L N-ANT PINTO SALINAS' : '7911380',
        'L N-BRICE/O MENDEZ' : '7911720',
        'L N-C DEL V RODRIGUEZ' : '7912145',
        'L N-CAJIGAL' : '7911900',
        'L N-CRUZ DEL V RODRIGUEZ' : '7912140',
        'L N-FELIPE GUEVARA ROJAS' : '7913160',
        'L N-GUANIPA' : '7913470',
        'L N-L ANT PINTO SALINAS' : '7911380',
        'L N-NARCISO FRAGACHAN' : '7916800',
        'L N-TOMAS ALFARO CALATRAVA' : '7918760',
        'L.BOLIVARIANO CHAMARIAPA' : '7950516',
        'LB JOSE FRNACISCO LAYA' : '7950839',
        'LB SIMON RODRIGUEZ' : '7919780',
        'LIC TOMAS ALFARO C' : '7918750',
        'NER LAS PLACITAS' : '6942128',
        'NER-552' : '6970552',
        'NER-NUC ESC RURAL N 039' : '6970039',
        'NER-NUC ESC RURAL N 040' : '6970040',
        'NER-NUC ESC RURAL N 078' : '6970078',
        'NER-NUC ESC RURAL N 183' : '6970183',
        'NER-NUC ESC RURAL N 212' : '6970212',
        'NER-NUC ESC RURAL N 239' : '6970239',
        'NER-NUC ESC RURAL N 281' : '6970281',
        'NER-NUC ESC RURAL N 310' : '6970310',
        'NER-NUC ESC RURAL N 371' : '6970371',
        'NER-NUC ESC RURAL N 445' : '6970445',
        'NER-NUC ESC RURAL N 450' : '6970450',
        'NUCLEO ESCOLAR INDIGENA' : '6942110',
        'NUCLEO ZONA 02' : '6010002',
        'O M EDUC INDG Y Z FRONT' : '610700001',
        'OFIC DE SUPERV ZONA NO 02' : '6101200',
        'P E BARRIO EL ESFUERZO' : '4100607',
        'P E-JOSE FELIX RIVAS' : '4105104',
        'P E-MARIA MONTESSORI' : '4106778',
        'PE. FRANCISCO FERRER' : '6589862',
        'TEL AGUAPANE' : '6202205',
        'TEL PUERTO LA CRUZ' : '6490525',
        'TEV- TRONCONAL III' : '6505188',
        'U.E.D. DR. ALI GARCIA C.' : '6990045',
        'UE CINCUENTENARIO' : '6590044',
        'UE. DR. JOSE MARIA VARGAS' : '7950642',
    }
    
    id = models.CharField(primary_key=True, max_length=20, verbose_name="Cédula de Identidad")
    nombre=models.CharField(max_length=50, verbose_name="Apellidos y Nombres")
    cod_cargo=models.CharField(max_length=50,verbose_name="Cod_Cargo", blank=True, editable=False)
    profession=models.CharField(max_length=50, verbose_name="Profesión u Oficio", choices=PROFESSION_CHOICES)
    municipio=models.CharField(max_length=20, verbose_name="Municipio", choices=MUNICIPIO_CHOICES)
    cod_plantel=models.CharField(max_length=50,verbose_name="Cod_Plantel", blank=True, editable=False)
    plantel=models.CharField(max_length=50, verbose_name="Plantel", choices=PLANTEL_CHOICES)
    cuota = models.DecimalField(
        max_digits=8,  # Número máximo de dígitos en total (incluyendo los decimales)
        decimal_places=2,  # Número de decimales permitidos
        validators=[MinValueValidator(0.01)],  # Validador para valores mínimos
        verbose_name="Cuota"
    )
    fecha=models.DateTimeField(auto_now_add=True)
    
    def save(self, *args, **kwargs):
        self.cod_cargo = self.CARGO_CHOICES.get(self.profession, '')
        self.cod_plantel = self.CODPLANTEL_CHOICES.get(self.plantel, '')
        super().save(*args, **kwargs)
    
    def clean(self):
        # Eliminar espacios en blanco alrededor de los campos de texto
        self.id = self.id.strip()
        self.nombre = self.nombre.strip()
        self.cod_cargo = self.cod_cargo.strip()
        self.profession = self.profession.strip()
        self.municipio = self.municipio.strip()
        self.cod_plantel = self.cod_plantel.strip()
        self.plantel = self.plantel.strip()

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name='afiliado'
        verbose_name_plural='afiliados'
        