# Generated by Django 4.2.1 on 2023-08-08 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cédula de Identidad')),
                ('nombre', models.CharField(max_length=20, verbose_name='Apellidos y Nombres')),
                ('cod_cargo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cod_Cargo')),
                ('profession', models.CharField(max_length=50, verbose_name='Profesión u Oficio')),
                ('municipio', models.CharField(max_length=20, verbose_name='Municipio')),
                ('cod_plantel', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cod_Plantel')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa u organismo donde trabaja')),
            ],
            options={
                'verbose_name': 'afiliado',
                'verbose_name_plural': 'afiliados',
            },
        ),
    ]
