# Generated by Django 4.2.4 on 2023-08-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageWorkers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='profession',
            field=models.CharField(choices=[('99 NO CLASIFICADOS', '99 NO CLASIFICADOS'), ('BACHILLER I', 'BACHILLER I'), ('BACHILLER II', 'BACHILLER II'), ('BACHILLER III', 'BACHILLER III'), ('PROF. UNIV. MEDICO I', 'PROF. UNIV. MEDICO I'), ('PROF.UNIV. ODONTOLOGO I', 'PROF.UNIV. ODONTOLOGO I'), ('PROFESIONAL UNIV. I', 'PROFESIONAL UNIV. I'), ('PROFESIONAL UNIV. II', 'PROFESIONAL UNIV. II'), ('PROFESIONAL UNIV.III', 'PROFESIONAL UNIV.III'), ('TSU I', 'TSU I'), ('TSU II', 'TSU II')], max_length=50, verbose_name='Profesión u Oficio'),
        ),
    ]
