# Generated by Django 4.2.1 on 2023-08-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageWorkers', '0002_alter_afiliado_cod_cargo_alter_afiliado_cod_plantel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='cod_cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cod_Cargo'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='municipio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Profesión u Oficio'),
        ),
    ]
