# Generated by Django 4.2.4 on 2023-08-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageWorkers', '0004_alter_afiliado_cod_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='cod_cargo',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='Cod_Cargo'),
        ),
    ]
