# Generated by Django 4.2.1 on 2023-08-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageWorkers', '0004_alter_afiliado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='cod_cargo',
            field=models.CharField(default='', max_length=50, verbose_name='Cod_Cargo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='municipio',
            field=models.CharField(default='', max_length=20, verbose_name='Municipio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='profession',
            field=models.CharField(default='', max_length=50, verbose_name='Profesión u Oficio'),
            preserve_default=False,
        ),
    ]
