# Generated by Django 4.2.4 on 2023-09-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageWorkers', '0006_alter_afiliado_cod_plantel_alter_afiliado_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afiliado',
            old_name='empresa',
            new_name='plantel',
        ),
    ]
