# Generated by Django 4.2.4 on 2023-09-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageWorkers', '0007_rename_empresa_afiliado_plantel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afiliado',
            options={'permissions': [('can_import_afiliado', 'Can Import Afiliado Data')], 'verbose_name': 'afiliado', 'verbose_name_plural': 'afiliados'},
        ),
    ]
