# Generated by Django 4.2.4 on 2023-09-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageWorkers', '0008_alter_afiliado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afiliado',
            options={'permissions': [('can_import_afiliado', 'Can Import Afiliado Data'), ('can_export_afiliado', 'Can Export Afiliado Data')], 'verbose_name': 'afiliado', 'verbose_name_plural': 'afiliados'},
        ),
    ]
