# Generated by Django 4.2.4 on 2023-09-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageWorkers', '0009_alter_afiliado_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afiliado',
            old_name='nombre',
            new_name='primer_apellido',
        ),
    ]
