# Generated by Django 4.2.4 on 2023-09-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageWorkers', '0011_alter_afiliado_primer_apellido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Afiliado',
        ),
    ]
