# Generated by Django 4.2.4 on 2023-09-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageWorkers', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='segundo_apellido',
            field=models.CharField(max_length=20, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='segundo_nombre',
            field=models.CharField(max_length=20, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
