# Generated by Django 4.2.4 on 2023-09-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageWorkers', '0014_alter_afiliado_segundo_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='sexo',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=2, verbose_name='Sexo'),
        ),
    ]
